services:
  - type: web
    name: finmodai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 start.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

